sudo: false
dist: precise
language: php

php:
#  - 5.3
#  - 5.4
#  - 5.5
- 5.6
#  - 7.0

matrix:
  fast_finish: true
  #allow_failures:
  #  - php: 5.6
  exclude:
    # Newer Magento versions uses newer PHP versions
  - php: 5.3
    env: MAGENTO_VERSION="magento-mirror-1.9.3.1"
    # Old Magento Versions are not officially supported to run with PHP 5.5
  - php: 5.5
    env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
  - php: 5.5
    env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    # Old Magento Versions are not officially supported to run with PHP 5.6
  - php: 5.6
    env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
  - php: 5.6
    env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
  - php: 5.6
    env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
  - php: 5.6
    env: MAGENTO_VERSION="magento-mirror-1.9.0.1"
    # Old Magento Versions are not officially supported to run with PHP 7.0
  - php: 7.0
    env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
  - php: 7.0
    env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
  - php: 7.0
    env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
  - php: 7.0
    env: MAGENTO_VERSION="magento-mirror-1.9.0.1"

env:
  global:
  - MAGENTO_DB_ALLOWSAME=1
  - SKIP_CLEANUP=1
  - TEST_BASEDIR=.modman/Advocodo_Group/app/code/community/Advocodo/Group/Test
  matrix:
  - MAGENTO_VERSION="magento-mirror-1.6.2.0"
  - MAGENTO_VERSION="magento-mirror-1.7.0.2"
  - MAGENTO_VERSION="magento-mirror-1.8.1.0"
  - MAGENTO_VERSION="magento-mirror-1.9.3.1"

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"

before_install:
- test -n "$GITHUB_TOKEN" && echo "Found GitHub token" && composer config github-oauth.github.com "$GITHUB_TOKEN" || echo "No GitHub token found"

install:
- composer install --no-interaction
- phpenv rehash

script:
- mkdir -p build/logs
#- curl --retry 2 --retry-delay 5 -H "Authorization":"token $GITHUB_TOKEN" -f -sSL https://raw.githubusercontent.com/mehdichaouch/MageTestStand/master/setup.sh | bash
- curl --retry 2 --retry-delay 5 -H "Authorization":"token $GITHUB_TOKEN" -f -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash

before_deploy:
- ./bin/before_deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
  - travis_release/Advocodo_Group.*.tar.gz
  - /home/travis/build/advocodo/Advocodo_Group/var/connect/Advocodo_Group-0.1.0-RC6.tgz
  - $TRAVIS_BUILD_DIR/README.md
  on:
    branch: travis
    condition: "$AUTO_DEPLOY = true"
    repo: advocodo/Advocodo_Group
    tags: true

#after_success:
#- ./bin/set_tags.sh

#after_deploy:
#  - ./bin/notification.sh

notifications:
  email:
    on_success: never  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
